// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MloKxH6dpQIOvuiZFoQSKGpHw1F69hY',
    appId: '1:294591946836:web:6c4609bee397d4aaf84dc1',
    messagingSenderId: '294591946836',
    projectId: 'guardia-ddc04',
    authDomain: 'guardia-ddc04.firebaseapp.com',
    databaseURL: 'https://guardia-ddc04-default-rtdb.firebaseio.com',
    storageBucket: 'guardia-ddc04.firebasestorage.app',
    measurementId: 'G-QQM40K5GJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXq4uqBcU8SzKpw49Mv6PiL-uVwoZp35c',
    appId: '1:294591946836:android:d145d5d170f84594f84dc1',
    messagingSenderId: '294591946836',
    projectId: 'guardia-ddc04',
    databaseURL: 'https://guardia-ddc04-default-rtdb.firebaseio.com',
    storageBucket: 'guardia-ddc04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB228wmcbFaz5xahlE2kWdOc7HI9wtEF28',
    appId: '1:294591946836:ios:65653d3cfd782f83f84dc1',
    messagingSenderId: '294591946836',
    projectId: 'guardia-ddc04',
    databaseURL: 'https://guardia-ddc04-default-rtdb.firebaseio.com',
    storageBucket: 'guardia-ddc04.firebasestorage.app',
    iosBundleId: 'com.example.guardiaMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB228wmcbFaz5xahlE2kWdOc7HI9wtEF28',
    appId: '1:294591946836:ios:65653d3cfd782f83f84dc1',
    messagingSenderId: '294591946836',
    projectId: 'guardia-ddc04',
    databaseURL: 'https://guardia-ddc04-default-rtdb.firebaseio.com',
    storageBucket: 'guardia-ddc04.firebasestorage.app',
    iosBundleId: 'com.example.guardiaMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4MloKxH6dpQIOvuiZFoQSKGpHw1F69hY',
    appId: '1:294591946836:web:d98842733db87123f84dc1',
    messagingSenderId: '294591946836',
    projectId: 'guardia-ddc04',
    authDomain: 'guardia-ddc04.firebaseapp.com',
    databaseURL: 'https://guardia-ddc04-default-rtdb.firebaseio.com',
    storageBucket: 'guardia-ddc04.firebasestorage.app',
    measurementId: 'G-QYLG2S5CRN',
  );
}
